### ISSUE TITLE
Interested in a complete rewrite & maintenance.

### ISSUE THREAD

**Issue by vsnthdev** [jwalapc/Your-Portfolio-website#38]
## 🚨 The Problems

1️⃣  **Everyone is duplicating the entire website**, it's just unnecessary code repetition 🤷‍♂️

2️⃣  **The portfolio's design looks outdated**, the UI can be responsive and using modern technologies like Tailwind CSS

3️⃣  **People's avatars appear squished** when a non-square image is provided.

4️⃣  **The website isn't dynamic**, each time someone has to add a new portfolio, they have to touch HTML/CSS/JS code.

## ✅ The Solution

A complete rewrite of the backed which dynamically updates people's portfolios based on the information provided on their GitHub profile 👌

Your profile picture, your bio, your name are all taken from GitHub's API directly and you simply can contribute something like 👇

```yaml
entries:
    -   username: vsnthdev
        socials:
            twitter: vsnthdev
            youtube: vsnthdev
            linkedin: vsnthdev
            # more social links
        background: # image URL
    
    -   username: you!
        socials:
            twitter: you
            facebook: you
            discord: you
            # more social links
        background: # image URl
    
    # other people's profiles
```

**I find this project quite interesting and would love to develop and maintain it.**

**Can I contribute (send a PR) with a completely re-written core which can be deployed for free?**

Thank you 🙂
